package sdk

import (
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
)

// getSystemPath returns the system+user PATH (platform-dependent, implemented in path_*.go)
func getSystemPath() string {
	return getPlatformPath()
}

// GetSystemPath is the exported version for use by external packages
func GetSystemPath() string {
	return getPlatformPath()
}

// ResolveSystemCommand resolves cmd to the full path of the first matching
// binary, or "" when the command is not found.
//
// The login-shell PATH is scanned FIRST and exec.LookPath is only the
// fallback: GUI processes launched from Dock/Finder inherit a bare PATH
// (/usr/bin:/bin:...), so LookPath-first would resolve e.g. python3 to
// /usr/bin/python3 even when the user's terminal uses
// /opt/homebrew/bin/python3 — ImportPathSdk would then refuse the import as
// system-protected. The shell PATH is what "in PATH" means to the user, so
// it wins; LookPath stays as the fallback for hosts where the shell probe
// fails.
//
// The SVC-managed shims directory (~/.svc/shims) is excluded: shims there are
// generated by this app and route to the active SDK version. Counting them as
// "available in PATH" would (a) always show installed SDKs as
// pathConfigured=true even after the real SDK is uninstalled (until the orphan
// shim is cleaned up), and (b) mislead the import flow which uses this check
// to decide whether an external SDK exists outside SVC's management.
func ResolveSystemCommand(cmd string) string {
	shimsDir := svcShimsDir()
	sep := ":"
	exts := []string{""}
	if runtime.GOOS == "windows" {
		sep = ";"
		exts = []string{"", ".exe", ".cmd", ".bat"}
	}
	if p := resolveInPathDirs(getSystemPath(), sep, exts, cmd, shimsDir); p != "" {
		return p
	}
	if p, err := exec.LookPath(cmd); err == nil && !isInShimsDir(p, shimsDir) {
		return p
	}
	return ""
}

// resolveInPathDirs scans PATH directories in order and returns the first
// regular file named cmd (plus platform extensions). Empty entries and the
// SVC shims directory are skipped. Pure core of ResolveSystemCommand's scan,
// parameterized so tests can exercise ordering and shim exclusion on any host.
func resolveInPathDirs(pathEnv, sep string, exts []string, cmd, shimsDir string) string {
	for _, dir := range strings.Split(pathEnv, sep) {
		dir = strings.TrimSpace(dir)
		if dir == "" {
			continue
		}
		if isShimsDir(dir, shimsDir) {
			continue
		}
		for _, ext := range exts {
			p := filepath.Join(dir, cmd+ext)
			if info, err := os.Stat(p); err == nil && !info.IsDir() {
				return p
			}
		}
	}
	return ""
}

// IsCommandAvailable checks whether a command is available in the system PATH
// (a thin wrapper over ResolveSystemCommand kept for existing callers).
func IsCommandAvailable(cmd string) bool {
	return ResolveSystemCommand(cmd) != ""
}

// svcShimsDir returns the absolute path to the SVC shims directory (~/.svc/shims).
// Computed from the user home dir to avoid importing the config package (which
// would create a circular dependency: config -> sdk is not present, but keeping
// sdk free of config is the established layering in this package).
func svcShimsDir() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return ""
	}
	return filepath.Join(home, ".svc", "shims")
}

// isShimsDir reports whether dir equals the SVC shims directory (case-insensitive
// on Windows, exact on Unix). Cleans the path first to handle trailing slashes.
func isShimsDir(dir, shimsDir string) bool {
	if shimsDir == "" {
		return false
	}
	cleaned := filepath.Clean(strings.TrimSpace(dir))
	if runtime.GOOS == "windows" {
		return strings.EqualFold(cleaned, shimsDir)
	}
	return cleaned == shimsDir
}

// isInShimsDir reports whether the resolved binary path lives inside the SVC
// shims directory (i.e. the command found by LookPath is one of our own shims).
func isInShimsDir(binaryPath, shimsDir string) bool {
	if shimsDir == "" {
		return false
	}
	dir := filepath.Dir(filepath.Clean(binaryPath))
	return isShimsDir(dir, shimsDir)
}

// SvcShimsDir returns the absolute path to the SVC shims directory (~/.svc/shims).
// Exported for use by package main (resolveCommand) to exclude shims from PATH scans.
func SvcShimsDir() string {
	return svcShimsDir()
}

// IsShimsDirEntry reports whether a PATH entry equals the SVC shims directory.
// Exported for use by package main (resolveCommand).
func IsShimsDirEntry(dir, shimsDir string) bool {
	return isShimsDir(dir, shimsDir)
}

// IsShimsPath reports whether a resolved binary path lives inside the SVC
// shims directory. Exported for use by package main (resolveCommand).
func IsShimsPath(binaryPath, shimsDir string) bool {
	return isInShimsDir(binaryPath, shimsDir)
}

// SdkType defines the supported SDK types
type SdkType string

const (
	NodeJS  SdkType = "nodejs"
	JDK     SdkType = "jdk"
	Golang  SdkType = "go"
	Python  SdkType = "python"
	Rust    SdkType = "rust"
	Ruby    SdkType = "ruby"
	DotNet  SdkType = "dotnet"
	PHP     SdkType = "php"
	Perl    SdkType = "perl"
	Maven   SdkType = "maven"
	Gradle  SdkType = "gradle"
	Flutter SdkType = "flutter"
	Android SdkType = "android"
	Dart    SdkType = "dart"
)

// AllSdkTypes returns all supported SDK types (in display order)
func AllSdkTypes() []SdkType {
	return []SdkType{
		NodeJS, JDK, Golang, Python, Rust, Ruby, DotNet, PHP, Perl,
		Maven, Gradle,
		Flutter, Android, Dart,
	}
}

// SdkDisplayName returns the display name of an SDK
func SdkDisplayName(t SdkType) string {
	switch t {
	case NodeJS:
		return "Node.js"
	case JDK:
		return "JDK"
	case Golang:
		return "Go"
	case Python:
		return "Python"
	case Rust:
		return "Rust"
	case Ruby:
		return "Ruby"
	case DotNet:
		return ".NET"
	case PHP:
		return "PHP"
	case Perl:
		return "Perl"
	case Maven:
		return "Maven"
	case Gradle:
		return "Gradle"
	case Flutter:
		return "Flutter"
	case Android:
		return "Android"
	case Dart:
		return "Dart"
	default:
		return string(t)
	}
}

// VersionInfo describes an available remote version
type VersionInfo struct {
	Version     string `json:"version"`
	Major       int    `json:"major"`
	DownloadURL string `json:"downloadUrl"`
	FileName    string `json:"fileName"`
	IsLTS       bool   `json:"isLts"`
	ReleaseDate string `json:"releaseDate"`
}

// SdkStatus describes the local installation status of an SDK
type SdkStatus struct {
	SdkType           SdkType  `json:"sdkType"`
	DisplayName       string   `json:"displayName"`
	Configured        bool     `json:"configured"`     // configured in .svc
	PathConfigured    bool     `json:"pathConfigured"` // present in PATH but not in .svc
	PathVersion       string   `json:"pathVersion"`    // version detected in PATH
	CurrentVersion    string   `json:"currentVersion"`
	InstalledVersions []string `json:"installedVersions"`
	InstallPath       string   `json:"installPath"`
	NeedsSwitch       bool     `json:"needsSwitch"` // true if currentVersion is not in installedVersions (dangling reference)
	// SystemProtected marks a PATH copy that lives in a protected OS path
	// (e.g. macOS /usr/bin/python3) and therefore cannot be safely imported.
	// The UI hides the import action and guides the user to install instead.
	SystemProtected bool   `json:"systemProtected"`
	SystemPath      string `json:"systemPath"`
	// ExternalManager names the external version manager that owns the PATH
	// copy (e.g. "nvm-rust" or "nvm" for Node.js). SVC must not import such a
	// copy; the UI hides the import action and tells the user to keep using
	// that manager. Empty when the copy is standalone.
	ExternalManager string `json:"externalManager"`
	// PathBinary is the resolved absolute path of the PATH copy's binary
	// (SVC shims excluded). Set when PathConfigured is true so the UI can
	// show the user exactly which file the PATH command resolves to.
	PathBinary string `json:"pathBinary"`
}

// InstallProgress is the install progress (pushed to the frontend via Wails Events)
type InstallProgress struct {
	SdkType          SdkType `json:"sdkType"`
	Version          string  `json:"version"`
	Stage            string  `json:"stage"`   // "downloading" | "extracting" | "configuring_path" | "verifying" | "done" | "error"
	Percent          int     `json:"percent"` // 0-100
	Message          string  `json:"message"`
	DownloadedBytes  int64   `json:"downloadedBytes"`
	TotalBytes       int64   `json:"totalBytes"`
	SpeedBytesPerSec int64   `json:"speedBytesPerSec"`
	DownloadURL      string  `json:"downloadUrl"`
}

// ScanProgress reports per-SDK scan progress during GetAllSdkStatus (pushed
// to the frontend via Wails Events so the startup loading screen can show
// which SDK is being checked).
type ScanProgress struct {
	SdkType     SdkType `json:"sdkType"`
	DisplayName string  `json:"displayName"`
	Index       int     `json:"index"` // 1-based position in the scan
	Total       int     `json:"total"`
}

// PackageManagerInfo describes a package manager
type PackageManagerInfo struct {
	Name      string  `json:"name"`      // npm, yarn, pnpm, composer, pip
	Version   string  `json:"version"`   // current version
	Installed bool    `json:"installed"` // whether installed
	ParentSdk SdkType `json:"parentSdk"` // parent SDK type
}

// GlobalPackage describes one globally installed npm package
type GlobalPackage struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}
