// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function CancelInstall(arg1) {
  return window['go']['main']['App']['CancelInstall'](arg1);
}

export function CheckProxy(arg1) {
  return window['go']['main']['App']['CheckProxy'](arg1);
}

export function CheckSystemConflicts(arg1) {
  return window['go']['main']['App']['CheckSystemConflicts'](arg1);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function CleanInactiveVersions(arg1) {
  return window['go']['main']['App']['CleanInactiveVersions'](arg1);
}

export function CleanLogs() {
  return window['go']['main']['App']['CleanLogs']();
}

export function CleanTmpCache() {
  return window['go']['main']['App']['CleanTmpCache']();
}

export function DeleteLogFile(arg1) {
  return window['go']['main']['App']['DeleteLogFile'](arg1);
}

export function DetectPathVersion(arg1) {
  return window['go']['main']['App']['DetectPathVersion'](arg1);
}

export function DownloadUpdate(arg1, arg2) {
  return window['go']['main']['App']['DownloadUpdate'](arg1, arg2);
}

export function GetAllSdkStatus() {
  return window['go']['main']['App']['GetAllSdkStatus']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetDefaultEndpoints() {
  return window['go']['main']['App']['GetDefaultEndpoints']();
}

export function GetDefaultInstallPath() {
  return window['go']['main']['App']['GetDefaultInstallPath']();
}

export function GetEndpoints() {
  return window['go']['main']['App']['GetEndpoints']();
}

export function GetGlobalPackages(arg1) {
  return window['go']['main']['App']['GetGlobalPackages'](arg1);
}

export function GetInstallDir(arg1) {
  return window['go']['main']['App']['GetInstallDir'](arg1);
}

export function GetInstallPath() {
  return window['go']['main']['App']['GetInstallPath']();
}

export function GetLogContent(arg1) {
  return window['go']['main']['App']['GetLogContent'](arg1);
}

export function GetLogDir() {
  return window['go']['main']['App']['GetLogDir']();
}

export function GetLogFiles() {
  return window['go']['main']['App']['GetLogFiles']();
}

export function GetNpmRegistry() {
  return window['go']['main']['App']['GetNpmRegistry']();
}

export function GetPackageManagers(arg1) {
  return window['go']['main']['App']['GetPackageManagers'](arg1);
}

export function GetPathEntries() {
  return window['go']['main']['App']['GetPathEntries']();
}

export function GetRemoteVersions(arg1) {
  return window['go']['main']['App']['GetRemoteVersions'](arg1);
}

export function GetSdkDownloadURL(arg1, arg2) {
  return window['go']['main']['App']['GetSdkDownloadURL'](arg1, arg2);
}

export function GetSdkStatus(arg1) {
  return window['go']['main']['App']['GetSdkStatus'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStorageInfo() {
  return window['go']['main']['App']['GetStorageInfo']();
}

export function GetTmpCacheSize() {
  return window['go']['main']['App']['GetTmpCacheSize']();
}

export function HasUpdateBackup() {
  return window['go']['main']['App']['HasUpdateBackup']();
}

export function ImportLocalSdk(arg1, arg2) {
  return window['go']['main']['App']['ImportLocalSdk'](arg1, arg2);
}

export function ImportPathSdk(arg1) {
  return window['go']['main']['App']['ImportPathSdk'](arg1);
}

export function ImportSdk(arg1, arg2) {
  return window['go']['main']['App']['ImportSdk'](arg1, arg2);
}

export function InstallGlobalPackage(arg1) {
  return window['go']['main']['App']['InstallGlobalPackage'](arg1);
}

export function InstallPackageManager(arg1) {
  return window['go']['main']['App']['InstallPackageManager'](arg1);
}

export function InstallSdk(arg1, arg2) {
  return window['go']['main']['App']['InstallSdk'](arg1, arg2);
}

export function MigrateInstallPath(arg1) {
  return window['go']['main']['App']['MigrateInstallPath'](arg1);
}

export function RollbackUpdate() {
  return window['go']['main']['App']['RollbackUpdate']();
}

export function SaveEndpoints(arg1) {
  return window['go']['main']['App']['SaveEndpoints'](arg1);
}

export function SaveGithubToken(arg1) {
  return window['go']['main']['App']['SaveGithubToken'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectLocalDir() {
  return window['go']['main']['App']['SelectLocalDir']();
}

export function SelectLocalFile() {
  return window['go']['main']['App']['SelectLocalFile']();
}

export function SetNpmRegistry(arg1) {
  return window['go']['main']['App']['SetNpmRegistry'](arg1);
}

export function SwitchVersion(arg1, arg2) {
  return window['go']['main']['App']['SwitchVersion'](arg1, arg2);
}

export function UninstallGlobalPackage(arg1) {
  return window['go']['main']['App']['UninstallGlobalPackage'](arg1);
}

export function UninstallVersion(arg1, arg2) {
  return window['go']['main']['App']['UninstallVersion'](arg1, arg2);
}

export function UpdateGlobalPackage(arg1) {
  return window['go']['main']['App']['UpdateGlobalPackage'](arg1);
}

export function UpdatePackageManager(arg1) {
  return window['go']['main']['App']['UpdatePackageManager'](arg1);
}
