// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {update} from '../models';
import {sdk} from '../models';
import {logger} from '../models';
import {pathmgr} from '../models';
import {config} from '../models';
import {storage} from '../models';

export function ApplyUpdate():Promise<void>;

export function CancelInstall(arg1:string):Promise<void>;

export function CheckProxy(arg1:string):Promise<void>;

export function CheckSystemConflicts(arg1:string):Promise<Array<string>>;

export function CheckUpdate():Promise<update.UpdateInfo>;

export function CleanInactiveVersions(arg1:string):Promise<void>;

export function CleanLogs():Promise<void>;

export function CleanTmpCache():Promise<void>;

export function DeleteLogFile(arg1:string):Promise<void>;

export function DetectPathVersion(arg1:string):Promise<string>;

export function DownloadUpdate(arg1:string,arg2:string):Promise<void>;

export function GetAllSdkStatus():Promise<Array<sdk.SdkStatus>>;

export function GetAppInfo():Promise<update.AppInfo>;

export function GetDefaultEndpoints():Promise<Array<sdk.EndpointInfo>>;

export function GetDefaultInstallPath():Promise<string>;

export function GetEndpoints():Promise<Record<string, string>>;

export function GetGlobalPackages(arg1:string):Promise<Array<sdk.GlobalPackage>>;

export function GetInstallDir(arg1:string):Promise<string>;

export function GetInstallPath():Promise<string>;

export function GetLogContent(arg1:string):Promise<string>;

export function GetLogDir():Promise<string>;

export function GetLogFiles():Promise<Array<logger.LogFileInfo>>;

export function GetNpmRegistry():Promise<string>;

export function GetPackageManagers(arg1:string):Promise<Array<sdk.PackageManagerInfo>>;

export function GetPathEntries():Promise<Array<pathmgr.PathEntry>>;

export function GetRemoteVersions(arg1:string):Promise<Array<sdk.VersionInfo>>;

export function GetSdkDownloadURL(arg1:string,arg2:string):Promise<string>;

export function GetSdkStatus(arg1:string):Promise<sdk.SdkStatus>;

export function GetSettings():Promise<config.AppSettings>;

export function GetStorageInfo():Promise<Array<storage.StorageInfo>>;

export function GetTmpCacheSize():Promise<number>;

export function HasUpdateBackup():Promise<boolean>;

export function ImportLocalSdk(arg1:string,arg2:string):Promise<void>;

export function ImportPathSdk(arg1:string):Promise<void>;

export function ImportSdk(arg1:string,arg2:string):Promise<void>;

export function InstallGlobalPackage(arg1:string):Promise<void>;

export function InstallPackageManager(arg1:string):Promise<void>;

export function InstallSdk(arg1:string,arg2:string):Promise<void>;

export function MigrateInstallPath(arg1:string):Promise<void>;

export function RollbackUpdate():Promise<void>;

export function SaveEndpoints(arg1:Record<string, string>):Promise<void>;

export function SaveGithubToken(arg1:string):Promise<void>;

export function SaveSettings(arg1:config.AppSettings):Promise<void>;

export function SelectLocalDir():Promise<string>;

export function SelectLocalFile():Promise<string>;

export function SetNpmRegistry(arg1:string):Promise<void>;

export function SwitchVersion(arg1:string,arg2:string):Promise<void>;

export function UninstallGlobalPackage(arg1:string):Promise<void>;

export function UninstallVersion(arg1:string,arg2:string):Promise<void>;

export function UpdateGlobalPackage(arg1:string):Promise<void>;

export function UpdatePackageManager(arg1:string):Promise<void>;
